### ISSUE TITLE
Unable to disable the new features added in version 8.1

### ISSUE THREAD

**Issue by Wei-Winter** [roysix/infy-scroll#105]
### Description

The specific issue is: After updating to version 8.1, in the additional settings, I found this option is enabled by default:

Open links in a new tab when clicking on them (Recommended)

Starting from Page 1

Starting from Page 2

Then I wanted to disable it. After clicking to disable and reloading the extension, I found it was still enabled. I tried the same steps again but still couldn't disable it. Then I tried toggling other options in the additional settings, which could be enabled and disabled normally, but only this option could not be disabled.

### URL

None

### Version

8.1

### Browser

Orion

### OS

iOS

### Device

Phone

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related to the app and is not related to making it work with a specific website (including [how to make images load](https://github.com/sixcious/infy-scroll/wiki/Missing-Images-or-Blank-Pages))

**Comment by sixcious** [comment]
Hi Wei-Winter, thanks for opening this issue 💜

I don't have access to Orion/WebKit browsers, but I just tested this again on both Chromium and Firefox for Android and I'm unable to reproduce this on my end. Are you able to reproduce this on another browser/engine like Chrome or Firefox? There might be something browser-specific Orion (WebKit) is doing that is preventing the checkbox from being unchecked for you.

I don't currently officially support Orion/WebKit browsers, but one thing you can try doing is going to OPTIONS > DATA > Text Backup/Restore and setting `"linksNewTab": null` then clicking/touching the Restore Data button.

It sounds like the update from Version 8 to 8.1 may not have worked out well through Orion, so if that doesn't work, try resetting your data (OPTIONS > DATA > Reset Data) or uninstalling and reinstalling it again (backup your data first to be safe).

Let me know if that works for you.
