### ISSUE TITLE
希望加入中文支持

### ISSUE THREAD

**Issue by zffffff** [roysix/infy-scroll#11]
因为看不懂，或许我遇到的问题是可以通过设置进行解决的？
**Screenshots**
![image](https://user-images.githubusercontent.com/21136110/125412857-e267a980-e3f1-11eb-8a7b-c741c4df83b6.png)
谢谢

**Comment by roysix** [comment]
嗨 zffffff，感谢您打开此问题并使用 Infy！

抱歉，它在该网站上不起作用！如果没有看到网站，就很难确定。通常，一系列空页面表示我们能够找到下一个链接（Page 2、3、4、...），但该网站使用 JavaScript 动态加载每个页面的内容（AJAX），因此页面是空白的。图像也可能被延迟加载。另一种可能性是`Page Element Rule`不好，因此没有附加任何内容。

我将一一尝试以下操作（通过单击 Infy 的工具栏图标并单击`铅笔`图标，然后单击`ACCEPT`）：
1. 如果这已经处于`Element` Append Mode，请尝试选中`Element Iframe` 复选框
2. 将 Append Mode 更改为 `Iframe` 以在 iframe 模式下追加整个页面
3. 将附加模式更改为`Page`（或者如果使用`Element`附加模式，则将`Page Element Rule`调整为其他内容）。然后尝试`Scripts and Styles`对话框（右下角）并选中`Append each page's scripts (JavaScript)`。也右键单击并检查页面并尝试查看图像是否被延迟加载并尝试手动设置延迟加载属性

它可能只是一个非常复杂的网站，而 Infy 无法处理它。

如果你愿意，你可以私下[email me](https://github.com/roysix/infy-scroll/wiki/Help) URL。
 
如果这有帮助，请告诉我。感谢您使用 Infy！

---

Hi zffffff, thank you for opening this issue and for using Infy!

Sorry that it's not working on that site! Without seeing the website, it would be difficult to say for sure. Usually, a series of empty pages indicate that we are able to find the next link (Page 2, 3, 4, ...), but the website is using JavaScript to load each page's content dynamically (AJAX), so the pages are blank. The images might also be lazily loaded. Another possibility is that the `Page Element Rule` is bad, so nothing is getting appended.

I would try the following, one by one (by clicking Infy's Toolbar Icon and clicking the `Pencil` icon then click `ACCEPT`):
1. If this is already in `Element` Append Mode, try checking the `Element Iframe` checkbox
2. Change the Append Mode to `Iframe` to append the full page in iframe mode
3. Change the Append Mode to `Page` (or if using `Element` append mode, adjust the `Page Element Rule` to something else). Then try the `Scripts and Styles` Dialog (bottom right corner) and check `Append each page's scripts (JavaScript)`. Also Right Click and Inspect the page and try and see if the images are being lazily loaded and try to manually set the lazy load attribute

It could just be a very complex website and Infy can't work on it.

If you want to, you can [email me](https://github.com/roysix/infy-scroll/wiki/Help) the URL privately.

Let me know if this helps. Thanks for using Infy!
