### ISSUE TITLE
Previous versions

### ISSUE THREAD

**Issue by javi2man** [roysix/infy-scroll#13]
Hi! Where can i find the previous versions of your app?  i need one that actually works with fennec f-droid 68.12.0 for android. (with actual version 0.6.0.6 says addon downloading, but can't install)
Thanks in advance!!

**Comment by roysix** [comment]
Hi javi2man, thanks for using Infy and for opening this issue!

I increased the minimum browser version to 77 in the latest version of Infy so I can use some new JavaScript/RegEx features. So, if your browser is still based on something older like version 68, that just might be the issue.

Is it possible to update your fennec f-droid browser to something more recent? If you're open to trying something else, [Firefox Nightly lets you use extensions on Android](https://github.com/roysix/infy-scroll/wiki/Help#android-support) as well (which is what I personally use).

If you don't want to update or use Firefox Nightly, you can [email me](https://github.com/roysix/infy-scroll/wiki/Help#report-a-problem) and I can try and send you a modified Infy with a lower minimum browser version that might work. You'll need to know how to install it manually as a standalone zip file, though.

Hope this helps!
Thanks again for using Infy.

**Comment by javi2man** [comment]
The app is now working perfectly! Thanks for your time!
