### ISSUE TITLE
Rules doesn't save in Vivaldi

### ISSUE THREAD

**Issue by Smyl3** [roysix/infy-scroll#15]
Hi,
I installed the extension under Vivaldi browser, but when I set a rule and Accept it it works, but if I revisit that site nothing happens.
It seems that it doesn't save any rule I set at all.

**Environment**
If you can, please fill out as much as you can about your environment.
 - Device: PC
 - OS: Windows 10
 - Browser Vivaldi
 - Browser Version 4.3.2431.3 (Official Build) (64-bit)
 - Extension Version 0.6 β (03/30/21)

**Comment by roysix** [comment]
Hi Smyl3. Thanks for using Infy!

Before clicking the `ACCEPT Button`, you'll need to click the `Heart Button` and [Save the URL](https://github.com/roysix/infy-scroll/wiki/Help#saving-urls).

Hope that helps.

**Comment by Smyl3** [comment]
You are correct! Sorry for the report mate!
Thank you for the great and fast support!
