### ISSUE TITLE
Stopped working on Firefox

### ISSUE THREAD

**Issue by BubiBalboa** [roysix/infy-scroll#6]
**Describe the bug**
I get the error message "Oops — Sorry! Infy had trouble loading on this page. Infy might not have permission to work on this page (for example: Browser Pages, Options Page, or New Tab Page), or you might need to try refreshing this page again." 

I tried turning the addon off and on again. Reloaded the pages. Nothing helped. 

**URL**
Everywhere

**Environment**
Win 10 - Firefox 87.0b8

I think this started with the v87 Beta

**Comment by sixcious** [comment]
Hi BubiBalboa,

Sorry that it's not working. I just went ahead and installed Firefox Beta 87.0b8 and tested Infy and it seemed to still work fine.

What does it say in purple right below the text you quoted? The purple part is the actual error reason and is important. That message generally means there's something (like another extension) that's preventing Infy's `content script` from working on the page you're on.

Here are some things to try:

1. Can you try going to Infy's `Options` Page and note what you see? Are the Options pre-filled correctly or do they all look empty? Can you then go to the `About` section and try clicking the `Reset Options` Button to make sure your options aren't corrupted?
2. Try disabling all your other addons and see if Infy will start working. There have been confirmed cases in the past where another extension messed up Infy, namely in Firefox.
3. Try uninstalling and reinstalling Infy. This will ensure you start with a clean state that isn't corrupted. Make sure you do this in a Non-Private (Regular) Window.

Hope this helps and you get it working!

**Comment by BubiBalboa** [comment]
Resetting the options did it! As you said the options were all empty. 

I had another addon that reset a few settings  around the same time so maybe an update messed with the settings file or something. 

Anyway, thanks for your help and this great addon.
